### ISSUE TITLE
Erroring running dotnet run KeePass.DMP

### ISSUE THREAD

**Issue by Frxhb** [vdohney/keepass-password-dumper#11]
Hello There.
I created a KeePass dump from taskmanager and saved it to C:\Users\username\AppData\Local\TEMP\KeePass.DMP

Now when I try to run 

```dotnet run PATH_TO_DMP```

it says:

Es wurde kein ausführbares Projekt gefunden. Vergewissern Sie sich, dass unter C:\Users\Username\Downloads ein Projekt vorhanden ist, oder übergeben Sie den Pfad zum Projekt mithilfe von --project

(Username was censored)

Translated: No executable project was found. Make sure that there is a project under C:\Users\Username\Downloads or pass the path to the project using --project

I installed .Net 7 provided by your link.

Am I doing something wrong?

**Comment by Frxhb** [comment]
Ah I needed to clone this repository and run this command inside it. Sorry, now it works.

But I have loaded two keepass databases into my keepass app, but the password which was shown after running this isnt one of those two database master passwords.

**Comment by vdohney** [comment]
Glad you figured it out! Are those databases particularly old? If so, this issue is already being discussed here: https://github.com/vdohney/keepass-password-dumper/issues/4

Unfortunately, I hasn't been able to reproduce the issue, even when creating a DB with an old version of KeePass. If you happen to know which exact version of KeePass have you used to create them, it would be very helpful.

**Comment by Frxhb** [comment]
> Glad you figured it out! Are those databases particularly old? If so, this issue is already being discussed here: #4
> 
> Unfortunately, I hasn't been able to reproduce the issue, even when creating a DB with an old version of KeePass. If you happen to know which exact version of KeePass have you used to create them, it would be very helpful.

Oh, one of those databases are very old. I think almost or even older than 10 years. The other one maybe two years.

**Comment by vdohney** [comment]
Got it. If you happen to discover the particular versions, please post them to the issue above.
