### ISSUE TITLE
.Dmp not runing using cmd 

### ISSUE THREAD

**Issue by yahya3rd** [vdohney/keepass-password-dumper#13]
Hello I am pretty new to this can you help below problem 
.net 7 is installed and I copied the dmp file to desktop
![image](https://github.com/vdohney/keepass-password-dumper/assets/134431200/b00d90c0-f8c5-4a82-901f-482c2439284f)

**Comment by vdohney** [comment]
Hi, where have you cloned the repository? You should be in the project directory. Why are you on your desktop?

Please see: https://github.com/vdohney/keepass-password-dumper/issues/6#issuecomment-1559902204

**Comment by yahya3rd** [comment]
I didn't download it 🤡 like a bot I've spent 4 hours doing this and trying to figure out the issue (I don't know if this was just I waste of my time)

btw now I am getting result but not the password it's just some random characters
I've tried both memory mini dump
and task mgr dump file 
I also just changed it to this :
![image](https://github.com/vdohney/keepass-password-dumper/assets/134431200/23c04617-c167-4dad-84dd-e92423d248d4)
but the MEMORY.DMP didn't get created even though I've created a new keepass database

below is the result with no password showing:
![image](https://github.com/vdohney/keepass-password-dumper/assets/134431200/5e2033fb-ff9a-4efe-9a4a-a28596b2668f)

**Comment by vdohney** [comment]
What KeePass version are you on, please?

**Comment by vdohney** [comment]
Also, are you typing the master password on your keyboard? (not copy-pasting it)

**Comment by yahya3rd** [comment]
2.53.1 and yes

**Comment by yahya3rd** [comment]
do I need to login when I create the db or creating it is enough?

**Comment by vdohney** [comment]
Exactly, you need to decrypt the database ("login"), like a regular user would.

**Comment by yahya3rd** [comment]
OK THANK YOU IT KINDA WORKED I GOT HALF OF THE PASSWORD
I THINK THE ISSUE IN THE ABOVE RESULT IS THAT I CLOSE THE APP AND REOPEN THEN I DO THE TASKMGR DMP
WHEN I TRIED TO LOGIN AND KEEP THE SEESION OPEN AND DID THE TASKMGR DMP I GOT HALF OF THE PASSWORD
NOTE: THIS IS ALL CAPS BECAUSE I RELIZED HALFWAY THAT  I WAS TYPING IT ALL CAPS  SO GOT LAZY TO DELETE IT

**Comment by vdohney** [comment]
Lol, someone I know must be trolling me here
Anyway, glad you got it fixed :)
