### ISSUE TITLE
File size limit

### ISSUE THREAD

**Issue by oliveskur** [vdohney/keepass-password-dumper#2]
I got following error message:

Unhandled exception. System.IO.IOException: The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size.
   at System.IO.File.ReadAllBytes(String path)
   at Program.Main(String[] args) in C:\git\keepass-password-dumper-main\Program.cs:line 32

I used .NET SDK 7.0 and 2.5 GB pagefile.sys.

**Comment by vdohney** [comment]
Hi oliveskur, thanks for reporting the issue!

I was too lazy to implement this properly, so during testing I just split the file into smaller ones. It will be resolved shortly.

**Comment by vdohney** [comment]
Fixed.
