### ISSUE TITLE
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point  XPTO.csp roj

### ISSUE THREAD

**Issue by Rapinarius** [vdohney/keepass-password-dumper#6]
Hey 

Thanks for the code and program and all the work.

I'm stuck at an error that its generated in Powershell when I run  "dotnet run keepass.DMP"
I'm using the keepass process DMP.

error:

----------------------------------------------------------------------------
 CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [XPTO.csp
roj]
Dotnet : 
At line:1 char:1
+ dotnet run KeePass.DMP
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The build failed. Fix the build errors and run again.
---------------------------------------------------------------------

Can you please help?

Thanks in advanced.
Best Regards,

**Comment by vdohney** [comment]
Hi, we should be able to figure this one out! Are you actually in the project directory? It seems like it can’t find `Program.cs`.

If yes, please describe all the steps you took to get to this point.

**Comment by Rapinarius** [comment]
Hey,  

I have created a folder to work on and placed it at the desktop.
In that folder I have placed; the KeepPass.DMP file, the program.cs, and the keepass_password_dumper.csproj .

I have installed .net 7.xx , and had to place the .net install folder manually in the system paths.

Now I'm running the command "dotnet run keepass.DMP" , because I'm already in the folder path..

Am I doing anything wrong?

Thanks in advanced for the help.

**Comment by vdohney** [comment]
_I have installed .net 7.xx , and had to place the .net install folder manually in the system paths._ - I think this might be related to this. I didn't have to do any of that when installing .NET. I would bet that it's actually looking for the Program.cs somewhere else than you think. 

I've just tested it and I get the same error message only when I delete the Program.cs file. Could you please post a screenshot of your terminal, where you do `cat Program.cs`, `ls`, and then just `dotnet run`? 

Also, you can try running a C# hello world. This really seems more related general .NET issues than to this project. 

Where is .NET installed and how have you added it to PATH?

**Comment by vdohney** [comment]
What does `where.exe dotnet` say?

**Comment by Rapinarius** [comment]
hey,

--------------
 where.exe dotnet
C:\Program Files (x86)\dotnet\dotnet.exe

### I copied the KeepPass.DMP file, the program.cs, and the keepass_password_dumper.csproj .to the dotnet folder.
--------------------

PS C:\WINDOWS\system32> where.exe dotnet
C:\Program Files (x86)\dotnet\dotnet.exe

PS C:\WINDOWS\system32> cd\

PS C:\> cd 'C:\Program Files (x86)\dotnet'

PS C:\Program Files (x86)\dotnet> dotnet run keepass.dmp
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [C:\Program Files (x86)\dotnet\keepass_password_dumper.csproj.cs
proj]
dotnet : 
At line:1 char:1
+ dotnet run keepass.dmp
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The build failed. Fix the build errors and run again.

PS C:\Program Files (x86)\dotnet> 

thanks for your help

**Comment by vdohney** [comment]
You shouldn't be in the `C:\Program Files (x86)\dotnet` or copy anything there.

You should clone the **whole repository** to somewhere like your desktop, then enter it (`cd keepass-password-dumper`) and then do the `dotnet run <path to dump>`. Make sure that `Program.cs` is the same directory as you are.

**Comment by Rapinarius** [comment]
Sorry , did what you describe but still got the the same error msg.

CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [C:\Users\fredt\Desktop\WareHouse\powershell\dotnet\keepass_pass
word_dumper.csproj.csproj]

**Comment by vdohney** [comment]
Did you? What is `keepass_password_dumper.csproj.csproj`? There's no such file in the project. You obviously aren't in the project directory.

Please do exactly this: https://github.com/vdohney/keepass-password-dumper#setup

**Comment by Rapinarius** [comment]
Hey,,
Thanks I can make it work now, using your howto.
The issue was all along the hiden and wrong file extentions, that I added to your original files...
  My Bad :-(

Anyway I still coould not get the Master Pass or Key, becouse I had a old DB file that I lost the pw for.
And it seems that this way we cannot get the password for that un-used at this pc, DB. ..
any idea how I can eventually proced ?

If not, thanks anyway, and keep up the excellent work and great support you give us all.

Regards,

**Comment by vdohney** [comment]
Glad you figured it out!

There actually might be a way to recover that password with this tool. Read more on how the vulnerability works, I think it's quite obvious. 

However, please understand that I am unable to verify what your intent is (you might as well have stolen someone's laptop for all I know). For that reason, I won't provide you with exact steps. I hope that makes sense.
